if ( WIN32 OR WIN64 OR MINGW OR MING32 OR MINGW64 ) # WINDOWS
    set( PLATFORM "windows" )
    set( HEX_WINDOWS ON )
    add_definitions( -DHEX_WINDOWS=1 )
elseif ( ANDROID )
    set( PLATFORM "android" )
    set( HEX_ANDROID ON )
    add_definitions( -DHEX_ANDROID=1 )
elseif ( LINUX )
    set( PLATFORM "linux" )
    set( HEX_LINUX ON )
    add_definitions( -DHEX_LINUX=1 )
elseif ( MAC )
    set( PLATFORM "mac" )
    set( HEX_MAC ON )
    add_definitions( -DHEX_MAC=1 )
elseif ( IOS )
    set( PLATFORM "ios" )
    set( HEX_IOS ON )
    add_definitions( -DHEX_IOS=1 )
else ( WIN32 OR WIN64 OR MINGW OR MING32 OR MINGW64 )
    message( FATAL_ERROR "${PROJECT_NAME} - failed to detect target-platform, configuration required" )
endif ( WIN32 OR WIN64 OR MINGW OR MING32 OR MINGW64 )

add_definitions( -DHEX_PLATFORM_DEFINED=1 )

message ( STATUS "${PROJECT_NAME} - platform is ${PLATFORM}" )